version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Pre-Build Phase started...
      - echo "Environment details:"
      - sh mvnw --version
      - java -version
      - echo "git details:"
      - git log --name-status HEAD^..HEAD
      - echo Pre-Build Phase finished...
  build:
    commands:
      - echo Build Phase started...
      - echo Build started on `date`
      - sh mvnw clean install
      - echo Build Phase finished...
  post_build:
    commands:
      - echo Post-Build Phase started...
      - echo Create docker image
      - chmod +x docker/docker-build.sh
      - sh if [ $(git branch --show-current) == "master" ]; then docker/docker-build.sh; fi
      - echo Post-Build finished...
artifacts:
  files:
    - '**/*'


#reports:
#  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#    files:
#      - "**/*"
#    base-directory: 'target/tests/reports'
#    discard-paths: no
#  reportGroupCucumberJson:
#    files:
#      - 'cucumber/target/cucumber-tests.xml'
#    discard-paths: yes
#    file-format: CUCUMBERJSON # default is JUNITXML
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
#  discard-paths: yes
#  secondary-artifacts:
#    artifact1:
#      files:
#        - target/artifact-1.0.jar
#      discard-paths: yes
#    artifact2:
#      files:
#        - target/artifact-2.0.jar
#      discard-paths: yes
#cache:
#  paths:
#    - '/root/.m2/**/*'
